### ISSUE TITLE
Unsupported version of Ruby version 2.0.0

### ISSUE THREAD

**Issue by cwadding** [aha-app/aha-services#64]
Is there a reason that the gemfile is specifying version 2.0.0?
https://github.com/aha-app/aha-services/blob/master/Gemfile#L3

This is now an unsupported version. I get the following when I install 2.0.0 with rbenv:

```
WARNING: ruby-2.0.0-p645 is past its end of life and is now unsupported.
It no longer receives bug fixes or critical security updates.
```

Is there a plan to upgrade?

**Comment by schneidmaster** [comment]
Sorry for the delayed response -- we were in the process of upgrading. Issue is resolved by 158c8e8.
